#!/usr/bin/env bash
echo "Found .npmrc at: $npmrc_path"

NPM_TOKEN=$(UNMASK=true tefe npmrc-authtoken //npm.pkg.github.com/)

if [[ -z "$NPM_TOKEN" ]]; then
  echo "Necessary tokens not found in .npmrc, cannot proceed with build."
  exit 1
fi

# Modify Docker build to use tokens
# To debug it helps to use:  --no-cache \
docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile.build \
    --build-arg NPM_TOKEN="$NPM_TOKEN" \
    -t instance-intermediate \
    --load .

docker images | grep instance-intermediate

docker build \
    --progress=plain \
    -f Dockerfile \
    --build-arg BASE_IMAGE=instance-intermediate \
    --build-arg BASE_IMAGE=instance \
    -t instance-local \
    --load .

docker images | grep instance-local