#!/usr/bin/env bash
echo "Found .npmrc at: $npmrc_path"

# Create temp file, and remove on exit
trap 'rm -f ./instance.sbom.json' EXIT;
echo "{}" > ./instance.sbom.json


# Modify Docker build to use tokens
# To debug it helps to use:  --no-cache \
docker build \
    --no-cache \
    --progress=plain \
    -f Dockerfile.build \
    -t instance-intermediate \
    --load .

docker images | grep instance-intermediate

docker build \
    --progress=plain \
    -f Dockerfile \
    --build-arg BASE_IMAGE=instance-intermediate \
    -t instance-local \
    --load .

docker images | grep instance-local